[package]
name = "esp8266-hal"
version = "0.4.0"
authors = ["Robin Appelman <robin@icewind.nl>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "An experimental hardware abstraction layer for the esp8266"
repository = "https://github.com/esp-rs/esp8266-hal"
readme = "README.md"

[dependencies]
embedded-hal = { version = "0.2.4", features = ["unproven"] }
esp8266 = "0.2.0"
nb = "0.1.3"
void = { version = "1.0.2", default-features = false }
xtensa-lx-rt = { version = "0.5.0", optional = true, features = ["lx106"] }
xtensa-lx = "0.3.0"
paste = { version = "1.0", optional = true }
esp8266-hal-proc-macros = { version = "=0.1.0", path = "procmacros" }

[features]
default = ["rt", "interrupt"]
rt = ["xtensa-lx-rt"]
# Place program completely in RAM (needed when e.g. using only ROM bootloader, or for debugging).
all_in_ram = []
interrupt = ["paste"]

[profile.dev]
lto = true

[profile.release]
lto = true

[dev-dependencies]
panic-halt = "0.2.0"
enc28j60 = { version = "0.3.0", git = "https://github.com/icewind1991/enc28j60", branch = "feat_smoltcp", features = ["smoltcp"] }
smoltcp = { version = "0.7.1", default-features = false, features = ["ethernet", "proto-ipv4", "socket-raw", "socket-udp", "socket-tcp", "socket-icmp"] }